sudo: required

before_install:
  - wget https://saw.galois.com/builds/nightly/saw-0.2-2018-03-12-CentOS7-64.tar.gz
  - tar -xvzf saw-0.2-2018-03-12-CentOS7-64.tar.gz
  - export PATH=$PATH:$PWD/saw-0.2-2018-03-12-CentOS7-64/bin/
  - ./install_z3_yices.sh "$(mktemp -d)" "$PWD/z3bin"
  - $PWD/z3bin/bin/z3 --version
  - export PATH=$PATH:$PWD/z3bin/bin

compiler: clang

language: c

script: make saw

notifications:
  email:	
    recipients:	
      - nicole6953@gmail.com
      - nahugh2@tycho.ncsc.mil

    on_success:	always
    on_failure: always







