language: c

sudo: required

before_install:
  - eval "${MATRIX_EVAL}"

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: "deb http://ftp.us.debian.org/debian stretch stable"
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - z3
      env:
        - MATRIX_EVAL="wget https://saw.galois.com/builds/nightly/saw-0.2-2018-03-12-CentOS7-64.tar.gz && tar -xvzf saw-0.2-2018-03-12-CentOS7-64.tar.gz && export PATH=\$PATH:\$PWD/saw-0.2-2018-03-12-CentOS7-64/bin/"

    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="brew update && brew install z3"

script: make saw

notifications:
  email:	
    recipients:	
      - nicole6953@gmail.com
      - nahugh2@tycho.ncsc.mil

    on_success:	always
    on_failure: always
